######################
## Necessary Params ##
######################

Reference:
  ## Time
  separate_time_stamp: false #[true]:Set secs_stamp_column and nsecs_stamp_column / [false]:Set stamp_column
  #--------true--------#
  secs_stamp_column: 0
  nsecs_stamp_column: 0
  #--------false-------#
  stamp_column: 1

  ## Position
  x_column: 3
  y_column: 4
  z_column: 5

  ## Rotation
  use_quaternion: false # [true]:Set Quaternion / [false]:Set Euler
  #--------true--------#
  # Quaternion
  ori_x_column: 0
  ori_y_column: 0
  ori_z_column: 0
  ori_w_column: 0
  #--------false-------#
  # Euler
  use_radian: true # [true]:radian / [false]:degree
  roll_column: 6
  pitch_column: 7
  yaw_column: 8

  ## TF
  tf_time: 0 #[s]
  tf_x: 0 #[m]
  tf_y: 0 #[m]
  tf_z: 0 #[m]
  tf_roll: 0 #[rad]
  tf_pitch: 0 #[rad]
  tf_yaw: 0 #[rad]
  inv_roll: 1 # 1 or -1
  inv_pitch: 1 # 1 or -1
  inv_yaw: 1 # 1 or -1


Result:
  separate_time_stamp: true #[true]:Set secs_stamp_column and nsecs_stamp_column / [false]:Set stamp_column
  #--------true--------#
  secs_stamp_column: 2
  nsecs_stamp_column: 3
  #--------false-------#
  stamp_column: 0

  ## Position
  x_column: 5
  y_column: 6
  z_column: 7

  ## Rotation
  use_quaternion: true # [true]:Set Quaternion / [false]:Set Euler
  #--------true--------#
  # Quaternion
  ori_x_column: 8
  ori_y_column: 9
  ori_z_column: 10
  ori_w_column: 11
  #--------false-------#
  # Euler
  use_radian: true # [true]:radian / [false]:degree
  roll_column: 0
  pitch_column: 0
  yaw_column: 0

  ## TF
  tf_time: 0 #[s]
  tf_x: 0 #[m]
  tf_y: 0 #[m]
  tf_z: 0 #[m]
  tf_roll: 0 #[rad]
  tf_pitch: 0 #[rad]
  tf_yaw: 0 #[rad]
  inv_roll: 1 # 1 or -1
  inv_pitch: 1 # 1 or -1
  inv_yaw: 1 # 1 or -1
  

# Display
use_radian: true # [true]:radian / [false]:degree
progress_info: 4 # trajectory graph -> [0]:no display, [1]: number, [2]:time, [3]:ros time, [4]:distance
interval: 50 # progress_info is [1]:per number [2]:per [s], [3]:per [s], [4]:per [m]

title_font_size: 14 
label_font_size: 10
ticks_font_size: 8

# Save
save_figures: false
save_extension_type: png # without "."
save_dataframe: false



############
## Option ##
############
use_lerp: false

# Dosplay ellipse (put 2D covariance in result file)
display_ellipse: false
covariance_xx_column: 0
covariance_xy_column: 0
covariance_yx_column: 0
covariance_yy_column: 0
