######################
## Necessary Params ##
######################

Reference:
  ## Time
  separate_time_stamp: true #[true]:Set secs_stamp_column and nsecs_stamp_column / [false]:Set stamp_column
  #--------true--------#
  secs_stamp_column: 2
  nsecs_stamp_column: 3
  #--------false-------#
  stamp_column: 0

  ## Position
  x_column: 5
  y_column: 6
  z_column: 7

  ## Rotation
  use_quaternion: true # [true]:Set Quaternion / [false]:Set Euler
  #--------true--------#
  # Quaternion
  ori_x_column: 8
  ori_y_column: 9
  ori_z_column: 10
  ori_w_column: 11

  #--------false-------#
  # Euler
  use_radian: true # [true]:radian / [false]:degree
  roll_column: 8
  pitch_column: 9
  yaw_column: 10


Result:
  separate_time_stamp: true #[true]:Set secs_stamp_column and nsecs_stamp_column / [false]:Set stamp_column
  #--------true--------#
  secs_stamp_column: 2
  nsecs_stamp_column: 3
  #--------false-------#
  stamp_column: 0

  ## Position
  x_column: 5
  y_column: 6
  z_column: 7

  ## Rotation
  use_quaternion: true # [true]:Set Quaternion / [false]:Set Euler
  #--------true--------#
  # Quaternion
  ori_x_column: 8
  ori_y_column: 9
  ori_z_column: 10
  ori_w_column: 11

  #--------false-------#
  # Euler
  use_radian: true # [true]:radian / [false]:degree
  roll_column: 8
  pitch_column: 9
  yaw_column: 10

# Display
use_radian: true # [true]:radian / [false]:degree
# font: Arial <Unimplemented>
title_font_size: 14 
label_font_size: 10
ticks_font_size: 8

# Save
save_figures: true
save_extension_type: png # without "."
save_dataframe: true


############
## Option ##
############
# <--coming soon-->
# execution_time_graph: false
# execuation_column: 0

# velocity_graph: false
# velocity_column:

##################
## Warning sign ##
##################
# <--coming soon-->
# 2D_error:
# 3D_error:
# ellipse_long_radius:
# ellipse_short_radius:



