######################
## Necessary Params ##
######################

Reference:
  topic_name: /localization/pose_twist_fusion_filter/pose_with_covariance_without_yawbias
  storage_id: sqlite3
  serialization_format: cdr
  ## TF
  tf_time: 0 #[s]
  tf_x: 0 #[m]
  tf_y: 0 #[m]
  tf_z: 0 #[m]
  tf_roll: 0 #[rad]
  tf_pitch: 0 #[rad]
  tf_yaw: 0 #[rad]
  inv_roll: 1 # 1 or -1
  inv_pitch: 1 # 1 or -1
  inv_yaw: 1 # 1 or -1

Result:
  topic_name: /localization/pose_estimator/pose_with_covariance
  storage_id: sqlite3
  serialization_format: cdr
  ## TF
  tf_time: 0 #[s]
  tf_x: 0 #[m]
  tf_y: 0 #[m]
  tf_z: 0 #[m]
  tf_roll: 0 #[rad]
  tf_pitch: 0 #[rad]
  tf_yaw: 0 #[rad]
  inv_roll: 1 # 1 or -1
  inv_pitch: 1 # 1 or -1
  inv_yaw: 1 # 1 or -1

# Display
use_radian: true # [true]:radian / [false]:degree
progress_info: 0 # trajectory graph -> [0]:no display, [1]: number, [2]:time, [3]:ros time, [4]:distance
interval: 0 # progress_info is [2]:per [s], [3]:per [s], [4]:per [m]

title_font_size: 14 
label_font_size: 10
ticks_font_size: 8

# Save
save_figures: true
save_extension_type: png # without "."
save_dataframe: true

############
## Option ##
############
use_lerp: false

display_ellipse: false
